name: test

on:
  workflow_dispatch:
  push:
    branches: 'test'

jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          curl 'https://github.com/vakaras/smauglys-ide/releases/download/1.59.1/SmauglysSetup-x64-1.59.1.exe' -Lo VSCodeSetup-x64.exe
        shell: bash

      - name: Try installing Smauglys.
        run: ./VSCodeSetup-x64.exe /LOG="$instdir\l1.txt" /ALLUSERS /SILENT
        shell: bash
