name: test

on:
  workflow_dispatch:
  push:
    branches: 'test'

jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          curl 'https://www.python.org/ftp/python/3.8.10/python-3.8.10-amd64.exe' -Lo PythonInstaller-x64.exe
        shell: bash

      - name: Try installing Smauglys.
        run: ./PythonInstaller-x64.exe /passive InstallAllUsers=1 PrependPath=1
        shell: bash
